name: Check Markdown Links

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.md'
  schedule:
    # Run weekly on Monday to catch broken links
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  check-links:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Check Links
        run: npm run check:links || find . -name "*.md" -not -path "./node_modules/*" | xargs -n1 npx markdown-link-check -c .markdown-link-check.json -q
          
      - name: Report Results
        if: ${{ failure() }}
        run: |
          echo "Some links are broken! Please check the output above."
          echo "Run markdown-link-check locally to verify and fix broken links:"
          echo "npm install -g markdown-link-check"
          echo "markdown-link-check path/to/markdown/file.md"
