name: Markdown Lint

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  markdown-lint:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run markdownlint
        run: npx markdownlint "**/*.md" --ignore node_modules
